/**
 * Stable, typed recognition copy. These phrases are keys as well as the English
 * fallback so recognizer output cannot introduce an untranslated display value.
 */
export const DISK_RECOGNITION_LANGUAGE_KEYS = [
  ".NET",
  "APFS clone group",
  "APFS shared blocks",
  "Agent configuration, sessions, and cache — review before changing",
  "Agent configuration, sessions, or managed checkouts — keep it out of cleanup",
  "Agent sessions, configuration, projects, and history — review before changing",
  "Agent sessions, configuration, skills, and worktrees — review before changing",
  "Agent worktrees",
  "Apple",
  "Apps re-create as needed",
  "Apps re-create this as needed",
  "Build cache",
  "Build-tool data",
  "Bun user data",
  "Bun package cache",
  "Bun re-downloads packages",
  "Bundler cache",
  "C / C++",
  "Cache directory",
  "Cargo data",
  "Cargo re-downloads dependencies",
  "Cargo registry",
  "Cargo user data",
  "Claude Code agent home",
  "Claude Code data",
  "Claude Code-managed checkout",
  "CocoaPods dependencies",
  "Codex data",
  "Codex agent home",
  "Codex-managed checkout",
  "Coding agent data",
  "Coding agents",
  "Coding-agent data",
  "Common generated name, but verify before removing",
  "Containers",
  "Contains binaries, credentials, configuration, and disposable registries",
  "Contains configuration as well as caches; inspect a precise subfolder",
  "Contains configuration as well as package caches",
  "Counted at another path",
  "Dart / Flutter",
  "Dart build cache",
  "Developer build output",
  "Developer dependencies",
  "Developer toolchain cache",
  "Developer tooling",
  "Docker data",
  "Empty or restore it through Windows",
  "Empty or restore it through your operating system's Trash",
  "Filesystem metadata, snapshots, shared blocks, or restricted data",
  "Framework build output",
  "Generated build output",
  "Git",
  "Git manages this metadata — keep it",
  "Git or other VCS manages this data — keep it out of cleanup",
  "Git worktree",
  "Git worktree metadata",
  "Git-managed checkout",
  "Go",
  "Go module cache",
  "Go re-downloads modules",
  "Gradle cache",
  "Gradle downloads or rebuilds it",
  "Gradle user data",
  "Hard-linked file",
  "Hidden space",
  "IDE data",
  "Image",
  "Ivy cache",
  "Ivy re-downloads dependencies",
  "Java / Kotlin",
  "Keep",
  "Linked Git checkout",
  "Linked checkout data — remove it through Git or the owning agent",
  "Linked checkout — remove it with git worktree remove",
  "Linked checkouts — remove them through Git or the owning agent",
  "Linked checkouts — remove them through the owning agent",
  "Log files",
  "Manage installed toolchains with rustup",
  "Manage with Git",
  "Managed worktree",
  "Maven build target",
  "Maven re-downloads dependencies",
  "Maven repository",
  "Maven user data",
  "May contain configuration, history, or active sessions",
  "May contain credentials and persistent volumes; manage it through Docker",
  "May contain device data; manage runtimes and devices through Xcode",
  "May contain installed tools, project releases, plugins, or configuration",
  "May contain settings and project state as well as caches",
  "Node dependencies",
  "Node.js",
  "NuGet data",
  "NuGet packages",
  "NuGet restores packages",
  "NuGet user data",
  "Open it to separate disposable caches from configuration",
  "OpenCode data",
  "OpenCode agent home",
  "Other",
  "Other paths may still reference these bytes",
  "Package cache",
  "Package dependencies",
  "Package-manager data",
  "Possible build output",
  "Possible build target",
  "Protected",
  "Python",
  "Python cache",
  "Rebuildable",
  "Rebuilt by the project framework",
  "Recompiled on next run",
  "Recreatable, but preserve the project lockfile first",
  "Recycle Bin",
  "Redownloadable",
  "Regenerated on next build",
  "Reinstallable",
  "Review first",
  "Review the project toolchain before removing",
  "Rust",
  "Rust build target",
  "Rust toolchains",
  "Selected folder",
  "Shared link",
  "System Trash",
  "The project build tool regenerates it",
  "The project package manager regenerates it",
  "The project package manager restores it",
  "The related toolchain recreates or re-downloads it",
  "The scanner found a conventional artifact but did not prove it is safe to remove automatically",
  "This clone group is charged once in the map. Moving one pathname may not free the shared allocation.",
  "This file links a worktree or submodule to its Git metadata",
  "This file may share APFS blocks. Moving one pathname does not guarantee that its displayed bytes become free.",
  "Unclassified",
  "Usually generated, but verify the project lockfile before removing",
  "Usually safe to clear",
  "Vendored dependencies",
  "Version history",
  "Version-control data",
  "Audio",
  "Video",
  "Virtual environment",
  "Web tooling",
  "Worktrees",
  "Xcode DerivedData",
  "Xcode Simulator data",
  "Xcode build data",
  "Xcode regenerates on next build",
  "Your git history — keep it",
  "Your package manager restores it from the project lockfile",
  "cargo clean regenerates it",
  "dart/pub regenerates it",
  "macOS caches",
  "mvn clean regenerates it",
] as const

export type DiskRecognitionLanguageKey = (typeof DISK_RECOGNITION_LANGUAGE_KEYS)[number]

export const DISK_RECOGNITION_LANGUAGE_TEXT = Object.fromEntries(
  DISK_RECOGNITION_LANGUAGE_KEYS.map((key) => [key, key]),
) as { readonly [Key in DiskRecognitionLanguageKey]: Key }
